

name: 'Deploy to AWS'

on:
  workflow_dispatch:
  push:
    branches: 
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    run: |
      echo 'Ttste:  '
      echo ${{ secrets.TEST_ENV }}
    uses: ./.github/workflows/pulumi.yml
    secrets: inherit
    # with:
    #   destroy: false